app = "cned"  # 앱 이름 (fly launch 시 설정된 이름)

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "icn"  # 원하는 리전 코드 (예: 도쿄 = nrt, 서울 = icn)

[build]
  dockerfile = "Dockerfile"

[env]
  # 환경변수 기본값 정의 가능하나, 민감한 값은 fly secrets 사용 추천
  PORT = "8080"

[[services]]
  internal_port = 8080  # Dockerfile과 동일하게 설정해야 함
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
